sudo: required

# Enable C++ support
language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

          packages:
            - g++-7
            - cmake
            - build-essential
            - tclsh

      env:
        - PATH=/usr/bin:$PATH
        - CC=gcc-7
        - CXX=g++-7
        - PREFIX=/usr/include

    - os: windows
      language: shell
      install:
        - choco install -y make
        - choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install -y visualstudio2019-workload-vctools

      env:
        - PREFIX=$TRAVIS_BUILD_DIR/install
        - CMAKE_GENERATOR=Ninja
        - CC=cl
        - CXX=cl
        - PATH=/c/make/bin:$PATH
        - PATH="/c/Program Files/Git/mingw64/bin:$PATH"

# Build steps
script:
  - cmake --version
  - make --version
  - echo 'puts [info patchlevel];exit 0' | tclsh
  - make clean
  - make
  - make test
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then make install; fi;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi;
  - make test_install
